### ISSUE TITLE
nap

### ISSUE THREAD

**Issue by movenap** [Liberluna/liberluna.github.io#125]
name:nap
使用可能な言語は、batch,C,Ruby,
経歴
2010年11月03日 兵庫でおんぎゃあああうひょおおおおれのじだいだあああああと生まれる(※大阪育ちです)

2014年?月?日 数学に恋をする。と同時に当時よく分からなかったパソコンの構造に憧れを持つ。

2015年中盤～2016年最初 三角関数に一目惚れ。

2016年春 頭部を骨折する。その時の影響で脳機能が低下。そん時の影響かそれまでは違った天パになる。

2016年夏 退院。入院中やってたお陰で将棋が上手くなる。

2019年?月?日 ほぼ人生初みたいなもんのパソコンに触る。すっごい興奮した。(知識だけはあったし)

2019年?月?日 scratchを知る。プログラムの楽しさを教わった。

2019年?月?日 アカウントが乗っ取られる。その時ハッカーが助けてくれて自分もこうなりたいと思った。(後にそのハッカーが
　　　　　　  乗っ取っていたことを知る。)あと今思えばパスワード6文字で規則性あって脆弱すぎる...

2020年?月?日 パソコンが学校の物だったこともあり、bat.fileをやろうと決心。かなり早く習得できた。んでC言語が必要不可欠
　　　　　　 と知り、C言語も習得。

2020年?月?日 初のハッカーとしての仕事。乗っ取られた友達のscratcherを救った！自己満足感ハンパなかった。

2020年?月?日 初めて人に恋をする。っつうか尊敬。(絵がえぐ上手だった)

2021年?月?日 bat.file(batch)を極める。何か分からんけど僕はこれがいいなと思った。あと田代砲習得。頼もしい仲間となった。

2021年?月?日 scratchアカウントがクラッカーによって消される。moveとnapに転生。後にthgie=game,move=anime,nap=hack,
　　　　　　 という振り分けになった。

2022年?月?日 初めてハッカーチームに招待される。「カラス洗脳連合」という名前だった。Maybe。ちなみに最年少。

2022年?月?日 一番尊敬していたscratcherさんの垢を救った。自己肯定感超激アップ！

2023年4月7日 忘れもしない ここ、Liberlunaに参加！

2023年5月?日 Rubyを習得。どうやってやったかは教えん。

終わりに
今んとこ新参ですが、頑張っていこうと思います！scratchではmove028とnap_teamでやってるのでフォローしてn(((
https://scratch.mit.edu/users/move028/
twitterも一応やってます(move028_113)
hacking依頼はhttps://scratch.mit.edu/users/nap_team/かmove028の方で！

**Comment by movenap** [comment]
いえい

**Comment by nakasyou** [comment]
いやクローズすな()

**Comment by nakasyou** [comment]
@movenap アイコンちょうだい

**Comment by EdamAme-x** [comment]
それissueやPRやなくて

**Comment by movenap** [comment]
> @movenap アイコンちょうだい

[https://scratch.mit.edu/projects/859911516/](url)ここにあります
