### ISSUE TITLE
利用規約の作成

### ISSUE THREAD

**Issue by nakasyou** [Liberluna/liberluna.github.io#5]
利用規約は必要である

**Comment by Pochi-Liberluna** [comment]
GPTに生成させよう

**Comment by nakasyou** [comment]
## 1. 定義
- 「本サービス」とは、“liberluna.github.io”ドメインの下にある全てのページのことを指します。
- 「ユーザー」とは、本サービスにアクセスしている物を示します。
## 2. 利用規約について
### a. 利用規約の変更
本利用規約は、Liberlunaが、いつでも変更することができます。
### b. 利用規約の同意
本利用規約は、ユーザーが本サービスにアクセスし、使用したことにより同意されます。同意する意志を持たないユーザーは、本サービスの使用を停止してください。
## 3. 禁止事項
本サービスでは、次の行為を禁止します。
- 本利用規約を守らないこと。
- 本サービスを、犯罪行為に利用すること。
## 4. 免責事項
### a. 本サービス利用による責任
本サービスを利用することによって生じた、トラブルや問題に関して、Liberlunaは一切の責任を負いません。
### b. 本サービスの停止
Liberlunaは、本サービスをいつでも停止することができます。また、停止した場合や、停止された場合、Liberlunaは一切の責任を負わないものとします。
## 5. その他の事項
### a. 多言語との矛盾
本利用規約の日本語版と、日本語以外の利用規約が競合した場は、本利用規約の日本語版を適応することとします。
### b. 解釈
本利用規約は、日本法に基づき解釈されるものとします。
## 変更
- 2022-05-27+09:00 制定
